### **Numpy** (Numeric Python)
- **numpy module** adds functionality to lists
- enables a flat **1D vector** be *reshaped* into a **2D matrix**
- for Data Science 2D matrices are important, because:
    - **2D** is the structure of a spreadsheet (rows x columns)
    - in Python a **Pandas DataFrame** is a "spreadsheet variable"


In [ ]:
# 1. If numpy import fails, install:
# %pip install numpy

In [1]:
# 2. import the numpy module, plus a few others
import numpy as np

In [2]:
# 3. Make a list of 240 consectuive numbers from 1-240:
nums = list(range(1,241))
print(nums)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

In [19]:
# make a numpy array so that we can reshape this in various 2D and even 3D configs
nums_arr = np.array(nums)
print(type(nums_arr))
print(nums_arr[10], type(nums_arr[10]))
print(nums_arr.shape, nums_arr.ndim, nums_arr[:20])

<class 'numpy.ndarray'>
11 <class 'numpy.int64'>
(240,) 1 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [11]:
# make some 2D configs from the 240 item vector
_20x12_arr = nums_arr.reshape(20,12)
print(type(_20x12_arr))
print(_20x12_arr.shape, _20x12_arr.ndim) # (20, 12)
print(_20x12_arr[:3])

<class 'numpy.ndarray'>
(20, 12) 2
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 34 35 36]]


In [14]:
# make a 3D tensor.. just has to multiply out to 240
# 10 rows of 12 cols of 2 items each
_10x12x2 = nums_arr.reshape(10,12,2)
print(_10x12x2.shape, _10x12x2.ndim) # (10, 12, 2) 3
print(_10x12x2)

(10, 12, 2) 3
[[[  1   2]
  [  3   4]
  [  5   6]
  [  7   8]
  [  9  10]
  [ 11  12]
  [ 13  14]
  [ 15  16]
  [ 17  18]
  [ 19  20]
  [ 21  22]
  [ 23  24]]

 [[ 25  26]
  [ 27  28]
  [ 29  30]
  [ 31  32]
  [ 33  34]
  [ 35  36]
  [ 37  38]
  [ 39  40]
  [ 41  42]
  [ 43  44]
  [ 45  46]
  [ 47  48]]

 [[ 49  50]
  [ 51  52]
  [ 53  54]
  [ 55  56]
  [ 57  58]
  [ 59  60]
  [ 61  62]
  [ 63  64]
  [ 65  66]
  [ 67  68]
  [ 69  70]
  [ 71  72]]

 [[ 73  74]
  [ 75  76]
  [ 77  78]
  [ 79  80]
  [ 81  82]
  [ 83  84]
  [ 85  86]
  [ 87  88]
  [ 89  90]
  [ 91  92]
  [ 93  94]
  [ 95  96]]

 [[ 97  98]
  [ 99 100]
  [101 102]
  [103 104]
  [105 106]
  [107 108]
  [109 110]
  [111 112]
  [113 114]
  [115 116]
  [117 118]
  [119 120]]

 [[121 122]
  [123 124]
  [125 126]
  [127 128]
  [129 130]
  [131 132]
  [133 134]
  [135 136]
  [137 138]
  [139 140]
  [141 142]
  [143 144]]

 [[145 146]
  [147 148]
  [149 150]
  [151 152]
  [153 154]
  [155 156]
  [157 158]
  [159 160]
  [161 162]
  

### **arr = np.array(list)** makes a numpy array from a list
- **arr.ndim** returns the number of dimenstions the array
- **arr.shape** returns the shape of the array as a **tuple**
  - **(num_rows,num_cols)** is the tuple of a numpy array
  -- **(num_rows,)** is a 1D **vector**
  -- **(num_rows,num_cols)** is a 2D **matrix**

In [ ]:
# "dimensions.png"

### **arr.reshape(num_rows,num_cols)**
- returns a new array or specified shape
- reshape inputs must multiply out to exact number of items in array

In [20]:
# challenge:
# 7. Make a numpy array of 12 consective ints from 1-12:
# [1 2 3 4 5 6 7 8 9 10 11 12]
# arr = np.array(range(1,13))
arr = np.arange(1,13)
# print the array and its shape
print(arr.shape)
print(arr)

(12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [21]:
# CHALLENGE A: from the 12 item array
# Make an array called _6x2_arr (6 rows x 2 cols):
_6x2 = arr.reshape(6,2)
# print the array and its shape
print(_6x2.shape)
print(_6x2)

(6, 2)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [22]:
# CHALLENGE B: from the 12 item array
# Make an array called _2x6_arr (2 rows x 6 cols):
_2x6 = arr.reshape(2,6)
# print the array and its shape
print(_2x6.shape)
print(_2x6)

(2, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### **arr_transposed = arr.transpose()**
- inverts the shape (6,2) original returns a (2,6) transposed version
- but the row values have become the col values, and vice-versa

In [23]:
# 8. Transpose the _6x2 into a new array:
# it will have (2,6) shape BUT nums order changes
transposed_6x2 = _6x2.transpose()
print(transposed_6x2.shape)
print(transposed_6x2)

(2, 6)
[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]]


### **list and 1D array (vector) selections**
- single item: **list[index]** or **arr[index]**
- multiple list items: **list[start_index:end_index_excl]**
- 1D arr items: **arr[start_index:end_index_index_excl]**

### **numpy array 2D (matrix) selections**
- numpy arrays allow 2D selections, which are not possible with a list:
- **_2D_slice = _2D_arr[row_start:row_end_excl,col_start:col_end_excl]**

In [24]:
# 9. Make tic-tac-toe shape:
#     Make a list of 9 "X" and "O" values
#.    Make a 3x3 array that looks like a tic-tac-toe board
#.    where X wins along the upper left diagonal
ttt = ["X", "X", "O", "O", "X", "O", "X", "O", "X"]
ttt_arr = np.array(ttt).reshape(3,3)
print(ttt_arr)

[['X' 'X' 'O']
 ['O' 'X' 'O']
 ['X' 'O' 'X']]


In [ ]:
#  CHALLENGE. Make "O" the winner by changing an "X" to "O":
#     in a numpy array instead of double square brackets [1][1]
#     you can use a comma separator inside single square brackets: [1,1]
print(ttt_arr[1])
print(ttt_arr[1][1])
ttt_arr[1][1] = 'O'
print(ttt_arr)
print(ttt_arr[1][1])
print(ttt_arr[0])
print(ttt_arr[1,1])
print(ttt_arr[0,0])
print(ttt_arr[2,2])

In [35]:
# 10. Get the 2x2 in the upper left corner of the ttt board:
# _2x2_UL = tic_tac_toe[row_start:row_end,col_start,col_end]
_2x2_ul = ttt_arr[:2,:2]
print(_2x2_ul)

[['X' 'X']
 ['O' 'O']]


In [36]:
# 11. Get the 2x2 in the lower right corner of the ttt board:
_2x2_lr = ttt_arr[-2:,-2:]
print(_2x2_lr)

[['O' 'O']
 ['O' 'X']]


In [40]:
# 14.  CHALLENGE: Make a chessboard as numpy array (no dataframe):
#     Make a list of 64 consecutive 2-digit ints (21-84 range)
#.    Make a numpy array with the 8x8 dimensions of a chessboard
#.    just let the random nums fill all 64 squares
chess_arr = np.arange(21,85).reshape(8,8)
print(chess_arr)

[[21 22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52]
 [53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68]
 [69 70 71 72 73 74 75 76]
 [77 78 79 80 81 82 83 84]]


In [62]:
# 12. CHALLENGE: Get the first number (21) in the chessboard,
# that value at row 0, col 0
print(chess_arr[0][0]) # must do double [][] for 2D list selection
print(chess_arr[0,0]) # 2D array selection can use single [,]

21
21


In [63]:
# 15. CHALLENGE: Get the upper right corner 3x3 of the 8x8 chessboard
# do not make a new ttt board of shape 3x3 from scratch -- slice the 3x3 out of the 8x8: print(chessboard[first_3_rows,last_3_cols])
ttt_ur = chess_arr[:3,-3:]
print(ttt_ur)

[[26 27 28]
 [34 35 36]
 [42 43 44]]


In [64]:
# 13. CHALLENGE: Get the first col of the chessboard:
print(chess_arr[:,0])
print()

# CHALLENGE: get the first 2 cols of the chessboard:
print(chess_arr[:,:2])
print()

[21 29 37 45 53 61 69 77]

[[21 22]
 [29 30]
 [37 38]
 [45 46]
 [53 54]
 [61 62]
 [69 70]
 [77 78]]



In [65]:
# CHALLENGE: Get the last row of the chessboard:
print(chess_arr[-1,:])
print()

# get the last 2 rows of the chessboard:
print(chess_arr[-2:,:])
print()


[77 78 79 80 81 82 83 84]

[[69 70 71 72 73 74 75 76]
 [77 78 79 80 81 82 83 84]]



In [66]:
# 14. Get the first 2 rows and last 2 rows:
print(chess_arr[[0,1,-2,-1],:])
print()

[[21 22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35 36]
 [69 70 71 72 73 74 75 76]
 [77 78 79 80 81 82 83 84]]



If you want the first N and last N rows without hard-coding specific indices, you can use **np.r_** to concatenate slice ranges cleanly.

In [53]:
# 14B. Get the first 2 rows and last 2 rows:
print(chess_arr[np.r_[:2, -2:]])
print()

[[21 22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35 36]]



In [54]:
# CHALLENGE: Get the last 2 rows and first 2 cols:
print(chess_arr[-2:,:2])
print()

[[69 70]
 [77 78]]



In [55]:
# 16. Get (3,3) tic-tac-toe board size array, starting in the upper left corner of the chessboard, but skipping every other row, so index 0,2,4 (NOT 0,1,2)
print(chess_arr[:5:2,:3])

[[21 22 23]
 [37 38 39]
 [53 54 55]]


In [58]:
# 17. Get the middle 4 rows (2-5), middle 4 cols (2-5)

print(chess_arr[2:6,2:6])

[[39 40 41 42]
 [47 48 49 50]
 [55 56 57 58]
 [63 64 65 66]]


In [60]:
# CHALLENGE. Get the middle 4 rows (2-5), all cols:
print(chess_arr[2:6,:])

[[37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52]
 [53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68]]


In [61]:
# 18. Get the middle 4 cols (2-5), all rows:
print(chess_arr[:,2:6])

[[23 24 25 26]
 [31 32 33 34]
 [39 40 41 42]
 [47 48 49 50]
 [55 56 57 58]
 [63 64 65 66]
 [71 72 73 74]
 [79 80 81 82]]


#### Square bracket selections work on strings, too
- **str[start_index,end_index_excl]**